config/routes.rb
GithubAPIGooglemaps::Application.routes.draw do
  resources :users do
    collection do
      get  :show_commiters
      post :get_commiters
    end
  end

  root :to => 'users#index'

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  attr_accessible :description, :forks, :issues, :language, :last_commit_sha, :name, :owner, :watchers
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :name, :location, :email, :type, :blog, :avatar_url, :company, :repos, :following, :followers, :public_repos, :public_gists
  acts_as_gmappable
  serialize :repos, Array

  def gmaps4rails_address
    "#{self.location}"
  end

  scope :with_location, where(" location != 'none' ")
  scope :without_location, where(:location => 'none' )
  scope :by_repo, lambda{|repo| where("repos LIKE '%#{repo}%' ")  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  def get_commiters
    begin
      client = Github.new
      repo = client.repos.get  params[:user], params[:repo] 
      @repo = Repo.where(:name => repo.name).first ? Repo.where(:name => repo.name).first : Repo.create(:name => repo.name, :owner => repo.owner.login, :language => repo.language, :forks => repo.forks, :watchers => repo.watchers, :description => repo.description, :issues => repo.open_issues)
      @commits = client.repos.commits.all  @repo.owner, @repo.name, {:per_page => 100, :sha => @repo.last_commit_sha}
      @repo.update_attribute(:last_commit_sha, @commits.last.sha)
      @users_login = []
      @commits.each do |commit|
        @users_login << commit.author.login if commit.author
      end
      @logins = @users_login.uniq!
      self.find_or_create_user(@logins, client)
      redirect_to show_commiters_users_path(:repo => params[:repo])
    rescue => e
      redirect_to '/', :notice => e.inspect
    end
  end
  
  def show_commiters
    client = Github.new
    @repo = Repo.where(:name => params[:repo]).first    
    @users = User.without_location.by_repo(@repo.name).all
    @issues = client.issues.list_repo @repo.owner, @repo.name, {:per_page => 10}
    @events = [] 
    (1..10).each do |i|
      events = client.events.repository(@repo.owner, @repo.name, {:page => i})
      events.each do |event|
        @events << event
      end       
    end
    @collaborators = client.repos.collaborators.list @repo.owner, @repo.name
    @json = User.with_location.by_repo(params[:repo]).to_gmaps4rails do |user, marker|
      marker.infowindow render_to_string(:partial => "/users/user", :locals => { :user => user})
      marker.title "#{user.name}"
    end
  end


  protected

  def find_or_create_user(logins, client)
    logins.each do |login|
      @user = User.where(:login => login).first
      unless @user
        user_info = client.users.get :user => login
        @user = User.create(:login        => login,
                    :name         => user_info.name,
                    :location     => user_info['location'].present? ? user_info['location'] : 'none',
                    :email        => user_info.email,
                    :type         => user_info.type,
                    :blog         => user_info.blog,
                    :repos        => [ params[:repo] ],
                    :avatar_url   => user_info.avatar_url,
                    :company      => user_info.company,
                    :following    => user_info.following,
                    :followers    => user_info.followers,
                    :public_repos => user_info.public_repos,
                    :public_gists => user_info.public_gists
        )
      else
        unless @user.repos.include?(params[:repo])
          @user.repos << params[:repo]
          @user.save
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def create_events_stats(events)
    n = events.count 
    commit  = []
    create  = []
    delete  = []
    download  = []
    follow  = []
    fork  = []
    fork_apply  = []
    gist  = []
    gollum  = []
    issue  = []
    issue_comment  = []
    member  = []
    public  = []
    pull  = []
    team  = []
    watch  = []
    push  = []
    pull_review  = []
    events.each do |event|
      if event.type == 'CommitCommentEvent'
        commit << event
      elsif event.type == 'CreateEvent'
        create << event
      elsif event.type == 'DeleteEvent'
        delete << event
      elsif event.type == 'DownloadEvent'
        download << event
      elsif event.type == 'FollowEvent'
        commit << event
      elsif event.type == 'ForkEvent'
        fork << event
      elsif event.type == 'ForkApplyEvent'
        fork_apply << event
      elsif event.type == 'GistEvent'
        gist << event
      elsif event.type == 'GollumEvent'
        gollum << event
      elsif event.type == 'IssuesEvent'
        issue << event
      elsif event.type == 'MemberEvent'
        member << event
      elsif event.type == 'IssueCommentEvent'
        issue_comment << event
      elsif event.type == 'PublicEvent'
        public << event
      elsif event.type == 'PullRequestEvent'
        pull << event
      elsif event.type == 'PullRequestReviewCommentEvent'
        pull_review << event
      elsif event.type == 'PushEvent'
        push << event
      elsif event.type == 'TeamAddEvent'
        team << event
      elsif event.type == 'WatchEvent'                                                                                                                               
        watch << event  
      end
    end
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Type' ) 
    data_table.new_column('number', 'Values')     

    data_table.add_rows([ ['CommitCommentEvent', commit.count*100/n],['CreateEvent', create.count*100/n],['DeleteEvent', delete.count*100/n],
                          ['DownloadEvent', download.count*100/n],['FollowEvent', follow.count*100/n],['ForkEvent', fork.count*100/n],
                          ['ForkApplyEvent', fork_apply.count*100/n],['GistEvent', gist.count*100/n],['GollumEvent', gollum.count*100/n],
                          ['IssueCommentEvent', issue_comment.count*100/n],['IssuesEvent', issue.count*100/n],['MemberEvent', member.count*100/n],
                          ['PublicEvent', public.count*100/n],['PullRequestEvent', pull.count*100/n],['PullRequestReviewCommentEvent', pull_review.count*100/n],
                          ['PushEvent', push.count*100/n],['TeamAddEvent', team.count*100/n],['WatchEvent', watch.count*100/n] ])
    option = { width: 400, height: 500, title: 'Last events graph (%)' }
    @chart = GoogleVisualr::Interactive::BarChart.new(data_table, option) 
    return @chart    
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %title
      GithubAPIGooglemaps
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    'gmaps4rails' 
    = javascript_include_tag "application"
    = javascript_include_tag "http://www.google.com/jsapi"
    = csrf_meta_tags
  %body
    = yield

  %footer
    = yield :scripts

app/views/users/_collaborator.html.haml
= link_to image_tag( collaborator.avatar_url, :size => "16x16" ), "https://github.com/#{collaborator.login}", :target => '_blank'  
&nbsp;
= link_to collaborator.login, "https://github.com/#{collaborator.login}", :target => '_blank'
.clear

app/views/users/_issue.html.haml
= link_to image_tag( issue.user.avatar_url, :size => "16x16" ), "https://github.com/#{issue.user.login}", :target => '_blank'  
&nbsp;
= link_to truncate( issue.title, :length => 70, :omission => '...'), issue.html_url, :target => '_blank'
.clear

app/views/users/_user.html.haml
%div
  = link_to image_tag(user.avatar_url, :size => "32x32"), "https://github.com/#{user.login}", :target => '_blank' 
  = user.name
  |   
  = link_to user.login, "https://github.com/#{user.login}", :target => '_blank' 
  .clear
  - unless user.location == 'none'
    location :
    = user.location
    .clear
  followers :
  = user.followers
  .clear
  following :
  = user.following
  .clear
  public_repos :
  = user.public_repos
  .clear
  public_gists :
  = user.public_gists
- if user.location == 'none'
  %hr{:style => "width:800px;float:left;"}
  .clear
  %br

app/views/users/index.html.haml
%h1
  Welcome
%p{:id => 'error'}
  = notice
%br
= form_tag get_commiters_users_path do
  = label_tag "User"
  = text_field_tag "user"
  %br
  = label_tag "Repo"
  = text_field_tag "repo"
  %br
  %input{:type=>"submit", :id=>"submit", :value=>"Submit", :disabled=>"disabled"} 

app/views/users/show_commiters.html.haml
%div{:style => "float:left;"}
  %h1
    Repository Information
  Name :
  = @repo.name
  .clear  
  Owner :
  = @repo.owner
  .clear
  Language :
  = @repo.language
  .clear
  Description :
  = @repo.description
  .clear
  Watchers :
  = @repo.watchers
  .clear
  Open Issues :
  = @repo.issues
  .clear
  Forks :
  = @repo.forks
  .clear
  %h1
    Graph
  %div{:id => 'chart'}
    = render_chart(create_events_stats(@events), 'chart')
  .clear
  %h1
    Collaborators
  - @collaborators.each do |collaborator|
    = render :partial => 'collaborator', :locals => {:collaborator => collaborator}
  .clear
  %h1
    Last 10 Issues
  - @issues.each do |issue|
    = render :partial => 'issue', :locals => {:issue => issue}
  .clear
%div{:style => "float:right;width:850px;"}
  %h1
    Committers With Location
  
  = gmaps4rails(@json)
  %br
  
  %h1
    Committers Without Location
  
  = render :partial => 'user', :collection => @users